version: '3.3'
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    links:
      - app
    volumes:
      - ./configs/person_list.conf:/etc/nginx/conf.d/person_list.conf
      - ./person_list/app/static:/static
    depends_on:
      - app
  app:
    build: person_list
    container_name: app
    command: sh -c './wait-for-it.sh database:5432 -- gunicorn -b 0.0.0.0:5000 runserver:app'
    expose:
      - "5000"
    links:
      - database
    volumes:
      - ./person_list:/code
    depends_on:
      - database
  database:
    build: database
    container_name: database
    expose:
      - "5432"
    volumes:
      - ./database/base:/var/lib/postgresql/data
